### ISSUE TITLE
Unable to Create Threshold Attributes

### ISSUE THREAD

**Issue by mrisher23** [TU-Berlin-SNET/JCPABE#1]
It appears that the logic put in place to 'fix' localization of numbers by converting ',' into '.' has made it impossible to create threshold gating.

The policy parsing indicates that it should be in the format of
    t = <NUMBER>
    <OF>
    "(" 
    Expression()
    (<COMMA> Expression())*
    ")"
    { jjtThis.setNumber(t.image); }

Which requires commas.

**Comment by IwoTens** [comment]
Thank you for reporting the issue. It should be fixed now. Please comment if it still does not work for you.
